Homework 1
regu1yar/smart-home-2020 pull request #1
Opened 2020-03-04 19:51 UTC by regu1yar

2020-03-10 07:44 UTC, a-ivanov requested changes

2020-03-10 07:44 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/handlers/CloseHallDoorEventHandler.java
> +            Door door = (Door) room.getSmartObjectByIdAndType(objectId, DOOR);
Странное API: клиент даёт ид и тип, а потом должен сам ещё раз кастовать и проверять, успешно ли прошёл каст... Нужно отдельно вести список типов для этого метода. Можно сделать проще?

2020-03-10 07:44 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/objects/Light.java
> +        SensorCommand command = new SensorCommand(CommandType.LIGHT_OFF, id);
Нарушение SRP, команду должен отправлять обработчик

2020-03-10 10:03 UTC, regu1yar commented on src/main/java/ru/sbt/mipt/oop/events/handlers/CloseHallDoorEventHandler.java
> +            Door door = (Door) room.getSmartObjectByIdAndType(objectId, DOOR);
Хотелось таким образом соблюсти OCP (писал как-то об этом в чате): сделать общий интерфейс для объектов умного дома, чтобы класс комнаты не раздувался с добавлением новых объектов, а можно было бы хранить все объекты в одной коллекции `private Map<SmartObjectType, Collection<SmartObject>> smartObjects`. Чтобы не кастовать тут, надо либо добавлять по методу для каждого типа объектов в класс комнаты, либо отказываться от общего интерфейса. Кажется, это все нарушает OCP.

2020-03-11 06:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/handlers/CloseHallDoorEventHandler.java
> +            Door door = (Door) room.getSmartObjectByIdAndType(objectId, DOOR);
Вы добавляете конкретные классы, тем самым расширяя доменную модель, в этом нет ничего плохого. 
Одну коллекцию можно использовать с единым для всех объектов алгоритмом. Этого здесь очевидно нет, поскольку вы делаете каст. Обработчики работают с конкретными объектами. 
Другой недостаток - вы фиксируете уровни вложенности объектов, при этом получая лишний непонятный каст. В дз 2 мы будем добавлять внутренний итератор в объекты, и ваша мапа потеряет смысл.
Переделайте обход объектов ближе к исходному варианту.

2020-03-11 21:15 UTC, regu1yar commented on src/main/java/ru/sbt/mipt/oop/events/handlers/CloseHallDoorEventHandler.java
> +            Door door = (Door) room.getSmartObjectByIdAndType(objectId, DOOR);
Переделал

2020-03-11 23:29 UTC, regu1yar commented on src/main/java/ru/sbt/mipt/oop/events/handlers/CloseHallDoorEventHandler.java
> +            Door door = (Door) room.getSmartObjectByIdAndType(objectId, DOOR);
<img width="915" alt="image" src="https://user-images.githubusercontent.com/34132385/76472886-e784a500-6407-11ea-85d4-1aed260a9ad0.png">
Кажется, это нельзя сделать без общего интерфейса и, собственно, каста, так как интерфейс Action не знает наперед к какому HomeComponent он будет применен. Или вы предлагаете у интерфейса Action заводить по методу для каждого компонента умного дома? Кажется, это нарушение принципа разделения интерфейсов. Вернусь к своему варианту, потому что как делать по-другому - неясно.

2020-03-12 17:01 UTC, a-ivanov requested changes

2020-03-12 17:01 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/handlers/DoorEventHandler.java
> +            Door door= room.getDoorById(objectId);
Зачем добавлять в апи метод getDoorById? Во первых, это нарушение OCP, мы можем захотеть добавить новый вид объектов в дом, и для их поиска придётся добавлять такой блок метод. Ввод вторых, в дз 2 мы добавим внутренний итератор и такие методы станут не нужны. Уберите их.

2020-03-12 17:01 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Room.java
> +    public Light getLightById(String id) {
Нарушение OCP при добавлении новых объектов в дом

2020-03-12 17:29 UTC, regu1yar commented on src/main/java/ru/sbt/mipt/oop/events/handlers/DoorEventHandler.java
> +            Door door= room.getDoorById(objectId);
Я об этом и писал выше, делал общий интерфейс для объектов и т.д. До прошлой итерации ревью у меня этих методов не было. Уже сделал часть про внутренние итераторы во втором дз - там этих методов тоже нет: https://github.com/regu1yar/smart-home-2020/pull/2.
Мне кажется, что если и требовать выполнение OCP в задании, то стоит делать это либо полностью, либо отложить на следующие дз.

2020-03-13 06:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/handlers/DoorEventHandler.java
> +            Door door= room.getDoorById(objectId);
Ну так правильно, до этого у вас OCP нарушался, теперь нарушается с этими методами. Если вы уже этим методы убрали в 2 дз, то перенести сюда не должно составить труда.

2020-03-13 06:46 UTC, a-ivanov requested changes
Перенесите исправления из 2 дз.

2020-03-15 20:38 UTC, a-ivanov approved these changes

2020-03-15 21:00 UTC, merged