Homework 3
regu1yar/smart-home-2020 pull request #3
Opened 2020-03-21 17:53 UTC by regu1yar

2020-03-24 07:52 UTC, a-ivanov requested changes

2020-03-24 07:52 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/handling/HandlerDecorator.java
> +        wrappee.handleEvent(event);
Отдельный класс, ради одного метода - мало плюсов, минусы см. в Effective Java, Item 20.

2020-03-24 07:52 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/types/EventType.java
> +    public static EnumSet<EventType> getSensorEvents() {
Ну раз так, то лучше уже делить на типы.

2020-03-24 07:52 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/security/SmartAlarmSystem.java
> +public class SmartAlarmSystem implements AlarmSystem {
Сигнализация не является состоянием, состояние - это ее имплементация, см. https://refactoring.guru/ru/design-patterns/state для примера и переделайте.

2020-03-24 07:52 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/security/AlarmSystemState.java
> +public enum AlarmSystemState {
Это надо убрать, это не шаблон состояние.

2020-03-24 10:58 UTC, regu1yar commented on src/main/java/ru/sbt/mipt/oop/security/SmartAlarmSystem.java
> +public class SmartAlarmSystem implements AlarmSystem {
Странно, на занятии делали так

2020-03-24 11:09 UTC, regu1yar commented on src/main/java/ru/sbt/mipt/oop/security/SmartAlarmSystem.java
> +public class SmartAlarmSystem implements AlarmSystem {
Без этого наследования наружу всегда будет торчать публичный метод `changeState` - это ок? Кажется, его нужно скрывать от пользователя и интерфейс успешно с этим справляется.

2020-03-24 11:11 UTC, regu1yar commented on src/main/java/ru/sbt/mipt/oop/security/SmartAlarmSystem.java
> +public class SmartAlarmSystem implements AlarmSystem {
Другой способ, как его скрыть - сделать состояния внутренними классами сигнализации, но это кажется еще хуже.

2020-03-26 10:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/security/SmartAlarmSystem.java
> +public class SmartAlarmSystem implements AlarmSystem {
> Странно, на занятии делали так

Маловероятно, осмелюсь предположить, что произошел misunderstanding.

2020-03-26 10:56 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/security/SmartAlarmSystem.java
> +public class SmartAlarmSystem implements AlarmSystem {
Мы инкапсулируем состояния внутри объекта (сигнализации). И просто делегируем им (возможно, нескольким) для выполнения действий. Т.е. операции в объекте (сигнализация) описываются в терминах операций в состоянии.

2020-03-26 10:56 UTC, a-ivanov requested changes
Поправьте по замечаниям.

2020-03-29 23:39 UTC, regu1yar commented
Добавил изменения в соответствии с 4 дз.

2020-03-30 15:40 UTC, a-ivanov commented
Уже обсуждали в группе, не надо делать несколько дз в одной ветке. Для каждого дз - своя ветка, свой пр.

2020-03-30 15:50 UTC, a-ivanov requested changes
3 дз - зачет. Перенесите код по 4 дз в отдельную ветку и создайте пр.

2020-03-30 15:50 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/events/SensorEventsManagerAdaptor.java
> +public class SensorEventsManagerAdaptor implements EventProcessor {
Вы чего к чему адаптируете? Перечитайте 4 задание и переделайте.

2020-03-30 15:50 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/applications/application/Application.java
> +        EventProcessor eventProcessor = context.getBean(EventProcessor.class);
По 4 дз см. текст задания в презентации. Надо использовать класс из сторонней библиотеки для итерации по событиям.

2020-03-30 16:56 UTC, regu1yar commented
> Уже обсуждали в группе, не надо делать несколько дз в одной ветке. Для каждого дз - своя ветка, свой пр.

Надо уточнить, что имеется в виду в строках "В одном пулл реквесте должен присутствовать код по соответствующей домашней работе, либо по нескольким, следующим подряд" - из [STUDENT_GUIDE.md](https://github.com/sbt-agoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md).

2020-03-30 17:08 UTC, regu1yar commented on src/main/java/ru/sbt/mipt/oop/smarthome/events/SensorEventsManagerAdaptor.java
> +public class SensorEventsManagerAdaptor implements EventProcessor {
Адаптирую класс из сторонней библиотеки для итерации по событиям к своему интерфейсу, который занимается тем же. Не очень понимаю, в чем проблема. В презентации ничего конкретного не сказано.

Делаю все в соответствии со статьей с https://refactoring.guru/ru/design-patterns/adapter.
![Adapter](https://user-images.githubusercontent.com/34132385/77940517-7840f900-72c1-11ea-8080-2e21b7b12edb.png)

Service - сторонний класс (в моем случае SensorEventsManager из сторонней библиотеки), Client Interface -  EventProcessor, мой интерфейс для итерации по событиям, Adapter - SensorEventsManagerAdapt**e**r, адаптер, реализующий этот интерфейс, делегирующий основную работу стороннему классу.

Я неправильно понял паттерн?

2020-03-30 18:05 UTC, regu1yar commented
3 дз вроде принято, мёржу. Продолжение обсуждения 4 дз тут: https://github.com/regu1yar/smart-home-2020/pull/4#issue-395810416

2020-03-30 18:06 UTC, merged