Hometask 4
regu1yar/smart-home-2020 pull request #4
Opened 2020-03-30 18:04 UTC by regu1yar

В продолжение к обсуждению из другого PR: https://github.com/regu1yar/smart-home-2020/pull/3#discussion_r400353841

2020-04-03 10:52 UTC, a-ivanov requested changes
Нужен адаптер стороннего обработчика событий к вашим.

2020-04-03 10:52 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/applications/application/Application.java
> +        EventProcessor eventProcessor = context.getBean(EventProcessor.class);
Ну вот ведь выше в com.coolcompany.smarthome.sample.Sample же приведен пример, как пользоваться сторонней библиотекой. В дз презентации это тоже сказано. Почему вы используете ее по-своему? Переделайте, как по заданию.

2020-04-03 10:52 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/applications/application/ApplicationConfiguration.java
> +        eventProcessor.registerHandler(new SecurityDecorator(new DoorEventHandler(smartHome), alarmSystem));
Обработчики - отдельными бинами https://bit.ly/2UrPgOg

2020-04-05 22:00 UTC, regu1yar commented on src/main/java/ru/sbt/mipt/oop/applications/application/Application.java
> +        EventProcessor eventProcessor = context.getBean(EventProcessor.class);
Переделал

2020-04-06 14:09 UTC, a-ivanov approved these changes

2020-04-06 14:09 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/events/handling/EventHandlerAdapter.java
> +        return ccEventTypesToEventTypes.get(event.getEventType()).createEvent(event.getObjectId());
Надо проверять наличие ключа.

2020-04-06 14:09 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/events/handling/EventHandlerAdapter.java
> +            "DoorIsOpen", new DoorOpenEventFactory(),
Тут общий алгоритм конвертации строк в Event и не обязательно делать по отдельной имплементации на строку. Можно воспользоваться лямбдами.

2020-04-06 14:09 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/applications/application/ApplicationConfiguration.java
> +    SensorEventsManager eventsManager(Map<String, EventHandler> handlers) {
Судя по вашему коду достаточно `List<EventHandler>`.

2020-04-06 18:27 UTC, merged