Homework 5
regu1yar/smart-home-2020 pull request #5
Opened 2020-04-01 17:51 UTC by regu1yar

2020-04-03 13:38 UTC, a-ivanov requested changes
А где конфигурация для команд? https://bit.ly/349z2MV

2020-04-03 13:38 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/applications/application/ApplicationConfiguration.java
> +        eventProcessor.registerHandler(new SecurityDecorator(new LightEventHandler(smartHome), alarmSystem));
Это все надо переделать по 4 дз

2020-04-05 22:43 UTC, regu1yar commented
> А где конфигурация для команд? https://bit.ly/349z2MV

Добавил

2020-04-06 14:14 UTC, a-ivanov approved these changes

2020-04-06 18:27 UTC, merged